SET NOCOUNT ON;
IF CAST(SERVERPROPERTY('ServerName') AS nvarchar(128)) <> N'DUNGDEV' OR DB_NAME() <> N'VideoFactory'
 THROW 51170, 'Unexpected database target.', 1;
BACKUP DATABASE [VideoFactory] TO DISK=N'D:\SQL2019\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\Backup\VideoFactory_before_cloud_20260910_003325.bak' WITH COPY_ONLY, CHECKSUM, COMPRESSION, STATS=25;
RESTORE VERIFYONLY FROM DISK=N'D:\SQL2019\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\Backup\VideoFactory_before_cloud_20260910_003325.bak' WITH CHECKSUM;