"""Offline speech-to-speech worker. No text/TTS/ASR or provider access.

OpenVoice and Demucs are loaded from verified component files by the desktop.
Requests are private JSON files generated by C#, never raw WebView payloads.
"""
import contextlib
import functools
import hashlib
import json
import os
from pathlib import Path
import socket
import sys

PROTOCOL = 1


def emit(kind, **values):
    print(json.dumps(dict(protocolVersion=PROTOCOL, type=kind, **values)), flush=True)


def deny_network(*_args, **_kwargs):
    raise RuntimeError("network_disabled")


@functools.lru_cache(maxsize=16384)
def check_directory(path):
    if path.is_symlink() or (path.lstat().st_file_attributes & 0x400 if os.name == 'nt' else False):
        raise ValueError("invalid_worker_path")


def resolve_beneath(root, name):
    root = Path(root)
    relative = Path(name)
    if relative.is_absolute() or not relative.parts or any(part in ('.', '..') for part in relative.parts):
        raise ValueError("invalid_worker_path")
    value = root / relative
    for parent in value.parents:
        check_directory(parent)
        if parent == root:
            break
    if value.is_symlink() or (value.exists() and value.lstat().st_file_attributes & 0x400 if os.name == 'nt' else False):
        raise ValueError("invalid_worker_path")
    return value


def long_path(path):
    value = os.path.abspath(path)
    return Path('\\\\?\\' + value) if os.name == 'nt' and not value.startswith('\\\\?\\') else Path(value)


def fit_length(audio, count, sr):
    import numpy as np
    if abs(len(audio) - count) > int(sr * 0.10):
        raise ValueError("timing_drift_exceeded")
    return np.pad(audio[:count], (0, max(0, count - len(audio))))


def speech_mask(count, windows, sr, fade_ms=20):
    import numpy as np
    mask = np.zeros(count, dtype=np.float32)
    for start, end in windows:
        if not (0 <= start < end <= count):
            raise ValueError("invalid_speech_window")
        mask[start:end] = 1
        fade = min(int(sr * fade_ms / 1000), (end - start) // 2)
        if fade:
            mask[start:start + fade] = np.linspace(0, 1, fade)
            mask[end - fade:end] = np.linspace(1, 0, fade)
    return mask


def file_hash(path):
    with path.open('rb') as stream:
        return hashlib.file_digest(stream, 'sha256').hexdigest()


def save_checkpoint(work, name, key, names):
    value = dict(key=key, files={entry: file_hash(resolve_beneath(work, entry)) for entry in names})
    partial = work / (name + '.part')
    partial.write_text(json.dumps(value), encoding='utf-8')
    partial.replace(work / name)


def cache_valid(work, name, key, names):
    try:
        checkpoint = json.loads((work / name).read_text(encoding='utf-8'))
        return checkpoint['key'] == key and set(checkpoint['files']) == set(names) and all(
            file_hash(resolve_beneath(work, entry)) == checkpoint['files'][entry] for entry in names)
    except (OSError, ValueError, KeyError, TypeError):
        return False


def run(request):
    if request.get("protocolVersion") != PROTOCOL:
        raise ValueError("protocol_mismatch")
    root = long_path(request["componentRoot"]).resolve(strict=True)
    manifest = json.loads((root / "manifest.json").read_text(encoding="utf-8-sig"))
    # The private request is created by the desktop after verifying every installed byte
    # BEFORE Python starts (including Python itself and site-package startup hooks).
    # Standalone invocation has no host seal and performs full verification here.
    host_verified = request.get('hostVerifiedManifestSha256') == file_hash(root / 'manifest.json')
    required_models = {
        'checkpoint.pth': '9652c27e92b6b2a91632590ac9962ef7ae2b712e5c5b7f4c34ec55ee2b37ab9e',
        'config.json': '9dfff60350b8c63f2c664efd92a61b2516efb22671466960f0e5dfebd881fa47',
        'demucs/955717e8-8726e21a.th': '8726e21a993978c7ba086d3872e7608d7d5bfca646ca4aca459ffda844faa8b4',
    }
    if not set(required_models).issubset({item['path'] for item in manifest['files']}):
        raise ValueError('runtime_checksum_invalid')
    for item in manifest["files"]:
        if item['path'] in required_models and item['sha256'] != required_models[item['path']]:
            raise ValueError('runtime_checksum_invalid')
        if host_verified and item['path'] not in required_models:
            continue
        path = resolve_beneath(root, item["path"])
        with path.open("rb") as stream:
            if path.stat().st_size != item["size"] or hashlib.file_digest(stream, "sha256").hexdigest() != item["sha256"]:
                raise ValueError("runtime_checksum_invalid")
    # Enforced before importing third-party runtime: even an accidental model lookup cannot upload/download.
    socket.socket.connect = deny_network
    socket.socket.connect_ex = deny_network
    socket.socket.sendto = deny_network
    socket.create_connection = deny_network
    socket.getaddrinfo = deny_network
    os.environ["HF_HUB_OFFLINE"] = "1"
    os.environ["TRANSFORMERS_OFFLINE"] = "1"
    os.environ["TORCH_FORCE_NO_WEIGHTS_ONLY_LOAD"] = "1"
    sys.path.insert(0, str(root / "openvoice"))
    import numpy as np
    import soundfile as sf
    import torch
    import torchaudio
    from silero_vad import load_silero_vad, get_speech_timestamps
    torch.set_num_threads(min(4, os.cpu_count() or 1))
    # Explicit Windows CPU compatibility profile: oneDNN primitive creation in
    # OpenVoice's reference encoder is not reliable on the validated laptop.
    torch.backends.mkldnn.enabled = False
    torch.manual_seed(0)
    device = "cpu"  # Reproducible MVP; CUDA admission requires its own measured profile.
    vad = load_silero_vad()
    from demucs.pretrained import get_model
    from demucs.apply import apply_model
    from openvoice.models import SynthesizerTrn
    from openvoice.mel_processing import spectrogram_torch
    from openvoice import utils

    config = utils.get_hparams_from_file(str(root / "config.json"))
    converter = SynthesizerTrn(0, config.data.filter_length // 2 + 1,
                              n_speakers=config.data.n_speakers, **config.model).to(device).eval()
    converter.load_state_dict(torch.load(root / "checkpoint.pth", map_location=device, weights_only=True)["model"], strict=True)
    # The Demucs checkpoint is pinned and verified above; its official loader needs architecture metadata.
    with contextlib.redirect_stdout(sys.stderr):
        separation = get_model("955717e8", repo=root / "demucs").to(device).eval()
    if request["action"] == "probe":
        # Exercise VAD and spectrogram path; content-quality acceptance is a separate opt-in smoke.
        get_speech_timestamps(torch.zeros(16000), vad, sampling_rate=16000)
        emit("completed", fingerprint=request["fingerprint"])
        return

    work = Path(request["workDirectory"]).resolve(strict=True)
    source = resolve_beneath(work, "source.wav")
    data, sr = sf.read(source, dtype="float32", always_2d=True)
    if sr != 48000 or data.shape[1] != 2 or not (sr <= len(data) <= sr * 9) or not np.isfinite(data).all():
        raise ValueError("invalid_source_audio")
    emit("progress", stage="DetectingSpeech")
    mono16 = torchaudio.functional.resample(torch.from_numpy(data.mean(axis=1)), sr, 16000)
    timestamps = get_speech_timestamps(mono16, vad, sampling_rate=16000,
                                       min_speech_duration_ms=200, speech_pad_ms=80)
    windows = [[max(0, t["start"] * 3), min(len(data), t["end"] * 3)] for t in timestamps]
    if not windows or sum(end - start for start, end in windows) < sr:
        raise ValueError("speech_not_detected")
    key = file_hash(source) + ':' + request['fingerprint']
    prepared_files = ['speech.wav', 'residual.wav']
    emit("progress", stage="SeparatingAudio")
    if cache_valid(work, 'prepared.json', key, prepared_files):
        speech, _ = sf.read(work / 'speech.wav', dtype='float32', always_2d=True)
        residual, _ = sf.read(work / 'residual.wav', dtype='float32', always_2d=True)
    else:
        mixture = torchaudio.functional.resample(torch.from_numpy(data.T), sr, separation.samplerate)
        with torch.inference_mode():
            separated = apply_model(separation, mixture[None], device=device, shifts=0,
                                    split=True, segment=4.0, overlap=0.25, progress=False, num_workers=0)[0]
        vocals = separated[separation.sources.index("vocals")]
        speech = torchaudio.functional.resample(vocals, separation.samplerate, sr).T.numpy()[:len(data)]
        residual = data - speech
        sf.write(work / 'speech.wav', speech, sr, subtype='FLOAT')
        sf.write(work / 'residual.wav', residual, sr, subtype='FLOAT')
        save_checkpoint(work, 'prepared.json', key, prepared_files)
    if len(speech) != len(data) or not np.isfinite(speech).all():
        raise ValueError("separation_invalid")
    (work / "windows.json").write_text(json.dumps(windows), encoding="utf-8")
    if request["action"] == "anchor":
        samples = np.concatenate([speech[a:b].mean(axis=1) for a, b in windows])
        if len(samples) < int(sr * 1.5):
            raise ValueError("anchor_too_short")
        sf.write(work / "anchor.wav", samples, sr, subtype="PCM_16")
        emit("completed")
        return
    if request["action"] != "convert":
        raise ValueError("invalid_action")
    anchor = resolve_beneath(work, "anchor.wav")
    conversion_key = key + ':' + file_hash(anchor)
    if cache_valid(work, 'conversion.json', conversion_key, ['converted.wav']):
        emit('completed')
        return
    reference, ref_sr = sf.read(anchor, dtype="float32")
    if reference.ndim != 1 or len(reference) < ref_sr * 1.5:
        raise ValueError("anchor_invalid")
    emit("progress", stage="ConvertingVoice")

    def spectrogram(wave, rate):
        y = torchaudio.functional.resample(torch.from_numpy(wave), rate, config.data.sampling_rate)[None]
        return spectrogram_torch(y, config.data.filter_length, config.data.sampling_rate,
                                 config.data.hop_length, config.data.win_length, center=False)

    with torch.inference_mode():
        reference_spec = spectrogram(reference, ref_sr)
        target_embedding = converter.ref_enc(reference_spec.transpose(1, 2)).unsqueeze(-1)
        source_mono = speech.mean(axis=1)
        source_reference = np.concatenate([source_mono[a:b] for a, b in windows])
        source_embedding = converter.ref_enc(spectrogram(source_reference, sr).transpose(1, 2)).unsqueeze(-1)
        spec = spectrogram(source_mono, sr)
        converted = converter.voice_conversion(spec, torch.LongTensor([spec.shape[-1]]),
                         sid_src=source_embedding, sid_tgt=target_embedding, tau=0.3)[0][0, 0]
        converted = torchaudio.functional.resample(converted, config.data.sampling_rate, sr).numpy()
    converted = fit_length(converted, len(data), sr)
    if not np.isfinite(converted).all() or np.max(np.abs(converted)) < 0.001:
        raise ValueError("conversion_inaudible")
    emit("progress", stage="Mixing")
    mask = speech_mask(len(data), windows, sr)
    # Preserve the native mixture outside speech windows and residual inside them.
    converted_rms = np.sqrt(np.mean(converted[mask > 0.5] ** 2) + 1e-9)
    source_rms = np.sqrt(np.mean(source_mono[mask > 0.5] ** 2) + 1e-9)
    converted *= min(2.0, max(0.5, source_rms / converted_rms))
    mix = data * (1 - mask[:, None]) + (residual + converted[:, None]) * mask[:, None]
    peak = np.max(np.abs(mix))
    if peak > 0.98:
        mix *= 0.98 / peak
    sf.write(work / "converted.wav", mix, sr, subtype="PCM_16")
    save_checkpoint(work, 'conversion.json', conversion_key, ['converted.wav'])
    emit("completed")


if __name__ == "__main__":
    try:
        request_path = Path(sys.argv[1])
        if request_path.stat().st_size > 32768:
            raise ValueError("request_too_large")
        req = json.loads(request_path.read_text(encoding="utf-8-sig"))
        # Third-party diagnostics must not emit filenames, model paths or raw audio metadata.
        with open(os.devnull, "w") as sink, contextlib.redirect_stderr(sink):
            run(req)
    except Exception as error:
        allowed = {"protocol_mismatch", "runtime_checksum_invalid", "invalid_worker_path", "network_disabled",
                   "invalid_source_audio", "speech_not_detected", "separation_invalid", "anchor_too_short",
                   "anchor_invalid", "conversion_inaudible", "timing_drift_exceeded", "request_too_large"}
        code = str(error) if str(error) in allowed else "local_voice_worker_failed"
        emit("error", code=code)
        sys.exit(1)
