param(
    [Parameter(Mandatory = $true)]
    [string]$SourceDirectory,

    [Parameter(Mandatory = $true)]
    [ValidatePattern('^[^\r\n]+$')]
    [string]$ExpectedVersion,

    [Parameter(Mandatory = $true)]
    [ValidatePattern('^[^\r\n]+$')]
    [string]$Source,

    [Parameter(Mandatory = $true)]
    [ValidatePattern('^[^\r\n]+$')]
    [string]$ApprovedBy,

    [Parameter(Mandatory = $true)]
    [ValidatePattern('^[^\r\n]+$')]
    [string]$LicenseReview,

    [ValidateSet('Development', 'Release')]
    [string]$ApprovalScope = 'Development',

    [string]$DestinationDirectory = '',

    [switch]$Force
)

$ErrorActionPreference = 'Stop'
$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$solutionRoot = [System.IO.Path]::GetFullPath((Join-Path $scriptRoot '..'))
$resolvedSource = [System.IO.Path]::GetFullPath($SourceDirectory)
$resolvedDestination = if ([string]::IsNullOrWhiteSpace($DestinationDirectory)) {
    Join-Path $solutionRoot 'third_party\ffmpeg\win-x64'
} else {
    [System.IO.Path]::GetFullPath($DestinationDirectory)
}

if (-not (Test-Path -LiteralPath $resolvedSource -PathType Container)) {
    throw "FFmpeg source directory does not exist: $resolvedSource"
}
if ($resolvedSource.TrimEnd('\', '/') -eq $resolvedDestination.TrimEnd('\', '/')) {
    throw 'SourceDirectory and DestinationDirectory must be different.'
}

$sourceFiles = @('ffmpeg.exe', 'ffprobe.exe', 'LICENSE.txt')
$profileFiles = @($sourceFiles + @('PROVENANCE.md', 'checksums.sha256'))
foreach ($fileName in $sourceFiles) {
    $path = Join-Path $resolvedSource $fileName
    if (-not (Test-Path -LiteralPath $path -PathType Leaf) -or (Get-Item -LiteralPath $path).Length -eq 0) {
        throw "FFmpeg source is missing required non-empty file: $fileName"
    }
}

New-Item -ItemType Directory -Force -Path $resolvedDestination | Out-Null
$existingProfileFiles = $profileFiles | Where-Object { Test-Path -LiteralPath (Join-Path $resolvedDestination $_) }
if ($existingProfileFiles.Count -gt 0 -and -not $Force) {
    throw "Destination already contains a bundle ($($existingProfileFiles -join ', ')). Use -Force only after approving replacement of these five profile files."
}

$stagingRoot = Join-Path ([System.IO.Path]::GetTempPath()) ("VideoMakerFfmpegBundle\{0}" -f [Guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Force -Path $stagingRoot | Out-Null
try {
    foreach ($fileName in $sourceFiles) {
        Copy-Item -LiteralPath (Join-Path $resolvedSource $fileName) -Destination (Join-Path $stagingRoot $fileName)
    }

    $checksumLines = foreach ($fileName in $sourceFiles) {
        $hash = (Get-FileHash -LiteralPath (Join-Path $stagingRoot $fileName) -Algorithm SHA256).Hash.ToLowerInvariant()
        "$hash *$fileName"
    }
    $checksumLines | Set-Content -LiteralPath (Join-Path $stagingRoot 'checksums.sha256') -Encoding utf8

    $acquiredUtc = [DateTime]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ssZ')
    @"
# FFmpeg bundle provenance

- Version: $ExpectedVersion
- Architecture: win-x64
- Source: $Source
- Acquired UTC: $acquiredUtc
- Approved by: $ApprovedBy
- License review: $LicenseReview
- Approval scope: $ApprovalScope

This profile was generated by scripts/Prepare-FfmpegBundle.ps1.
"@ | Set-Content -LiteralPath (Join-Path $stagingRoot 'PROVENANCE.md') -Encoding utf8

    $profile = & (Join-Path $scriptRoot 'Test-FfmpegBundle.ps1') `
        -BundlePath $stagingRoot `
        -ExpectedVersion $ExpectedVersion

    $backupRoot = Join-Path $stagingRoot 'backup'
    New-Item -ItemType Directory -Force -Path $backupRoot | Out-Null
    $createdFiles = @()
    foreach ($fileName in $profileFiles) {
        $destinationFile = Join-Path $resolvedDestination $fileName
        if (Test-Path -LiteralPath $destinationFile -PathType Leaf) {
            Copy-Item -LiteralPath $destinationFile -Destination (Join-Path $backupRoot $fileName)
        } else {
            $createdFiles += $destinationFile
        }
    }

    try {
        foreach ($fileName in $profileFiles) {
            Copy-Item -LiteralPath (Join-Path $stagingRoot $fileName) -Destination (Join-Path $resolvedDestination $fileName) -Force
        }

        $null = & (Join-Path $scriptRoot 'Test-FfmpegBundle.ps1') `
            -BundlePath $resolvedDestination `
            -ExpectedVersion $ExpectedVersion
    }
    catch {
        foreach ($createdFile in $createdFiles) {
            if (Test-Path -LiteralPath $createdFile -PathType Leaf) {
                Remove-Item -LiteralPath $createdFile -Force
            }
        }
        foreach ($fileName in Get-ChildItem -LiteralPath $backupRoot -File | Select-Object -ExpandProperty Name) {
            Copy-Item -LiteralPath (Join-Path $backupRoot $fileName) -Destination (Join-Path $resolvedDestination $fileName) -Force
        }
        throw
    }

    [pscustomobject]@{
        BundlePath = $resolvedDestination
        Version = $profile.Version
        FfmpegSha256 = $profile.FfmpegSha256
        FfprobeSha256 = $profile.FfprobeSha256
        LicenseSha256 = $profile.LicenseSha256
        ApprovalScope = $profile.ApprovalScope
    } | Format-List
}
finally {
    if ([System.IO.Directory]::Exists($stagingRoot)) {
        [System.IO.Directory]::Delete($stagingRoot, $true)
    }
}
